# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

#read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.05.01

# Environment Properties
minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)
neo_version=21.0.139-beta
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

## Mod Properties
mod_id=loginar
mod_name=Loginar Storage
mod_license=MIT
mod_version=1.4.2
release_type = release
mod_group_id=net.silentchaos512
mod_authors=SilentChaos512
mod_description=Adds new storage blocks and items, as well as alien squid dudes that may or may not attack you...
repo_name=loginar-storage
issue_tracker_url=https://github.com/SilentChaos512/Loginar-Storage/issues
display_url=https://github.com/SilentChaos512/Loginar-Storage/blob/1.21.x/README.md

## Dependencies
silentlib_version=10+
silentlib_version_range=[10.2,)
#silentgear_version=4.+
jei_version=19.+

## Curseforge
cf_project_id = 690569
cf_changelog_filename = CHANGELOG.md

## Modrinth
mr_project_id=loginar-storage
