modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/Loginar-Urns/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/loginar-urns"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512"

[[mods]]
    modId="loginar"
    version="${file.jarVersion}"
    displayName="Loginar Urns"
#    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Loginar-Urns/1.19.x/update.json"
    description='''
    TODO
    '''

[[dependencies.loginar]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.loginar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.loginar]]
    modId="silentlib"
    mandatory=true
    versionRange="[7.0.1,)"
    ordering="NONE"
    side="BOTH"
