modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/Loginar-Storage/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/loginar-storage"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512, giok3r"

[[mods]]
    modId="loginar"
    version="${file.jarVersion}"
    displayName="Loginar Storage"
#    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Loginar-Storage/1.19.x/update.json"
    description='''
    TODO
    '''

[[dependencies.loginar]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.loginar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.loginar]]
    modId="silentlib"
    mandatory=true
    versionRange="[7.2,)"
    ordering="NONE"
    side="BOTH"
