modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/Loginar-Storage/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/loginar-storage"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512, giok3r"

[[mods]]
    modId="loginar"
    version="${file.jarVersion}"
    displayName="Loginar Storage"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Loginar-Storage/1.20.x/update.json"
    description='''
    Adds new storage blocks and items, as well as alien squid dudes that may or may not attack you...
    '''

[[dependencies.loginar]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.loginar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.loginar]]
    modId="silentlib"
    mandatory=true
    versionRange="[8,)"
    ordering="NONE"
    side="BOTH"
