@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.loginar.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;