@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.loginar.crafting.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;