@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.loginar.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;